'use strict';

const GENERIC_MOTION_PROFILE = Object.freeze({
  profileId: 'generic-vrm',
  baseStandard: 'generic-vrm',
  capabilities: Object.freeze([]),
  walk: Object.freeze({
    speedScale: 1,
    cadence: 4.8,
    strideScale: 0.72,
    kneeLiftScale: 0.68,
    hipBobScale: 0.68,
    armSwingScale: 0.82,
  }),
  physics: Object.freeze({
    stepHz: 90,
    maxSubsteps: 4,
  }),
  handPose: Object.freeze({
    // Direct VRM imports use their authored wrist basis. PMX-specific
    // compensation is scoped to PMX_CONVERTED_MOTION_PROFILE below.
    palmFacingSign: 1,
    armAxisSign: 1,
    bodyForwardAxisSign: 1,
    legForwardAxisSign: 1,
    rootDepthAxisSign: 1,
    wristAmplitudeScale: 1,
    elbowBendScale: 1,
    fingerCurlScale: 1,
  }),
  legPose: Object.freeze({
    kneeBendSign: -1,
    seizaHipsDrop: 0.35,
    kneeHandReach: 0.68,
  }),
  springBone: Object.freeze({
    enabled: false,
    jointNamePatterns: Object.freeze([]),
    colliderSourcePatterns: Object.freeze([]),
    colliderTargetPatterns: Object.freeze([]),
    stiffnessScale: 1,
    dragForceAdd: 0,
    gravityPowerAdd: 0,
    hitRadiusScale: 1,
    copyColliderGroups: false,
  }),
});

// PMX-to-VRM imports generated by the bundled Blender pipeline use the MMD
// local-axis compensation below. Keep this in one place so the Electron import
// route and tests cannot drift apart. Ordinary VRM imports never reference it.
const PMX_CONVERTED_MOTION_PROFILE = Object.freeze({
  baseStandard: 'generic-vrm',
  capabilities: Object.freeze(['pmx-converted']),
  legPose: Object.freeze({
    // The MMD leg-forward axis is inverted below. The knee must bend in the
    // opposite direction to the thigh during a squat, not fold up behind it.
    kneeBendSign: 1,
  }),
  handPose: Object.freeze({
    // MMD Tools' mirrored wrist basis makes the normalized waving target
    // face away from the viewer unless the palm twist is inverted. This
    // override applies only to manifests generated by the PMX converter.
    palmFacingSign: -1,
    armAxisSign: -1,
    bodyForwardAxisSign: -1,
    legForwardAxisSign: -1,
    rootDepthAxisSign: -1,
    wristAmplitudeScale: 0.90,
    elbowBendScale: 1.16,
    fingerCurlScale: 1,
  }),
});

function clampNumber(value, fallback, minimum, maximum) {
  const number = Number(value);
  return Number.isFinite(number) ? Math.min(maximum, Math.max(minimum, number)) : fallback;
}

function sanitizePatterns(value) {
  if (!Array.isArray(value)) return [];
  return [...new Set(value
    .filter((item) => typeof item === 'string')
    .map((item) => item.trim().toLowerCase())
    .filter((item) => item.length >= 2 && item.length <= 64)
    .slice(0, 12))];
}

function sanitizeMotionProfile(value, { id, builtIn, verifiedYachiyo = false } = {}) {
  const candidate = value && typeof value === 'object' && !Array.isArray(value) ? value : {};
  const walk = candidate.walk && typeof candidate.walk === 'object' ? candidate.walk : {};
  const physics = candidate.physics && typeof candidate.physics === 'object' ? candidate.physics : {};
  const handPose = candidate.handPose && typeof candidate.handPose === 'object' ? candidate.handPose : {};
  const legPose = candidate.legPose && typeof candidate.legPose === 'object' ? candidate.legPose : {};
  const spring = candidate.springBone && typeof candidate.springBone === 'object' ? candidate.springBone : {};
  const capabilities = Array.isArray(candidate.capabilities)
    ? [...new Set(candidate.capabilities.filter((item) => ['long-garment', 'pmx-converted'].includes(item)))].slice(0, 4)
    : [];
  const springEnabled = capabilities.includes('long-garment') && spring.enabled === true;
  const yachiyoProfile = (builtIn === true && id === 'yachiyo') || verifiedYachiyo === true;

  return {
    // Imported characters always remain based on the generic standard. A
    // character-scoped capability may override parameters, but can never make
    // the application treat that model as the built-in Yachiyo asset.
    profileId: yachiyoProfile && typeof candidate.profileId === 'string'
      ? candidate.profileId.slice(0, 64)
      : 'generic-vrm',
    baseStandard: 'generic-vrm',
    capabilities,
    walk: {
      speedScale: clampNumber(walk.speedScale, GENERIC_MOTION_PROFILE.walk.speedScale, 0.45, 1.5),
      cadence: clampNumber(walk.cadence, GENERIC_MOTION_PROFILE.walk.cadence, 2.8, 7.2),
      strideScale: clampNumber(walk.strideScale, GENERIC_MOTION_PROFILE.walk.strideScale, 0.35, 1.15),
      kneeLiftScale: clampNumber(walk.kneeLiftScale, GENERIC_MOTION_PROFILE.walk.kneeLiftScale, 0.30, 1.2),
      hipBobScale: clampNumber(walk.hipBobScale, GENERIC_MOTION_PROFILE.walk.hipBobScale, 0.25, 1.2),
      armSwingScale: clampNumber(walk.armSwingScale, GENERIC_MOTION_PROFILE.walk.armSwingScale, 0.35, 1.2),
    },
    physics: {
      stepHz: Math.round(clampNumber(physics.stepHz, GENERIC_MOTION_PROFILE.physics.stepHz, 60, 120)),
      maxSubsteps: Math.round(clampNumber(physics.maxSubsteps, GENERIC_MOTION_PROFILE.physics.maxSubsteps, 2, 6)),
    },
    handPose: {
      palmFacingSign: Number(handPose.palmFacingSign) < 0 ? -1 : 1,
      armAxisSign: Number(handPose.armAxisSign) < 0 ? -1 : 1,
      bodyForwardAxisSign: Number(handPose.bodyForwardAxisSign) < 0 ? -1 : 1,
      legForwardAxisSign: Number(handPose.legForwardAxisSign) < 0 ? -1 : 1,
      rootDepthAxisSign: Number(handPose.rootDepthAxisSign) < 0 ? -1 : 1,
      wristAmplitudeScale: clampNumber(handPose.wristAmplitudeScale, 1, 0.65, 1.15),
      elbowBendScale: clampNumber(handPose.elbowBendScale, 1, 0.85, 1.25),
      fingerCurlScale: clampNumber(handPose.fingerCurlScale, 1, 0.65, 1.35),
    },
    legPose: {
      kneeBendSign: Number(legPose.kneeBendSign) > 0 ? 1 : -1,
      seizaHipsDrop: clampNumber(legPose.seizaHipsDrop, 0.35, 0.25, 0.65),
      kneeHandReach: clampNumber(legPose.kneeHandReach, 0.68, 0.45, 1.20),
    },
    springBone: {
      enabled: springEnabled,
      jointNamePatterns: springEnabled ? sanitizePatterns(spring.jointNamePatterns) : [],
      colliderSourcePatterns: springEnabled ? sanitizePatterns(spring.colliderSourcePatterns) : [],
      colliderTargetPatterns: springEnabled ? sanitizePatterns(spring.colliderTargetPatterns) : [],
      stiffnessScale: clampNumber(spring.stiffnessScale, 1, 0.35, 1.4),
      dragForceAdd: clampNumber(spring.dragForceAdd, 0, -0.20, 0.35),
      gravityPowerAdd: clampNumber(spring.gravityPowerAdd, 0, -0.10, 0.15),
      hitRadiusScale: clampNumber(spring.hitRadiusScale, 1, 0.8, 1.35),
      copyColliderGroups: springEnabled && spring.copyColliderGroups === true,
    },
  };
}

module.exports = {
  GENERIC_MOTION_PROFILE,
  PMX_CONVERTED_MOTION_PROFILE,
  sanitizeMotionProfile,
};
